site_name: TgCaller
site_description: Modern, fast, and reliable Telegram group calls library
site_url: https://tgcaller.github.io/TgCaller/
repo_url: https://github.com/TgCaller/TgCaller
repo_name: TgCaller/TgCaller

theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  language: en

nav:
  # (same as before...)

markdown_extensions:
  # (same as before...)

plugins:
  - search
  - sitemap
  - robots
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: true
  - meta
  # - mike  # if using versioned docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TgCaller/TgCaller
    - icon: fontawesome/brands/telegram
      link: https://t.me/TgCallerOfficial
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tgcaller/
  favicon: assets/favicon.ico
  social_image: assets/banner.png
  metadata:
    google-site-verification: o2I6YMzH3Qswem_bgJzIhJ-UbBQBPQxOuy2nY5y99fU
  copyright: |
    Copyright © 2024 TgCaller Team<br>
    Made with <span style="color: red;">&#10084;</span> for the Telegram developer community<br>
    <a href="https://tgcaller.github.io/TgCaller/">Documentation</a> |
    <a href="https://t.me/TgCallerOfficial">Community</a>

# google_analytics:
#   - "UA-XXXXXXX-X"
#   - auto
